fixtures:
  repositories:
    docker:
      repo: https://github.com/garethr/garethr-docker.git
      ref: v4.1.1
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
  symlinks:
    docker_hardening: "#{source_dir}"
